// ══════════════════════════════════════════════════════════════
//  DECEIVED — Scenario Bank
//  64 hand-written scenarios across 5 levels
//  Types: WHO_IS_LYING · AI_OR_HUMAN · BODY_LANGUAGE · CONSPIRACY_OR_FACT
// ══════════════════════════════════════════════════════════════

const LEVELS = [
  {
    id: 1,
    name: "The Rookie",
    tagline: "Learn to spot the obvious tells",
    difficulty: "Easy",
    color: "#00D4AA",
    scenarios: [
      { type:"WHO_IS_LYING", title:"The Alibi",
        setup:"A valuable watch goes missing from an office. Three coworkers were present.",
        statements:[
          {name:"Marcus",text:"I was in the break room the entire time. Sarah can confirm — we were talking about the Henderson project."},
          {name:"Sarah",text:"I was at my desk all morning. I didn't leave once. I had my headphones in."},
          {name:"Devon",text:"I stepped out for a client call around 10. Came back maybe 20 minutes later."},
        ], clue:"The Henderson project meeting was scheduled for the afternoon, not the morning.",
        liar:"Marcus", explanation:"Marcus claimed Sarah confirmed his alibi — but the Henderson meeting was in the afternoon. Sarah never confirmed his story. Devon's timeline checks out." },
      { type:"AI_OR_HUMAN", title:"Grief Message",
        setup:"One post in a grief support group was written by an AI pretending to mourn. Which one?",
        statements:[
          {name:"Post A",text:"It's been four months and I still reach for my phone to call her. I got to the 'M' in her name before I remembered."},
          {name:"Post B",text:"Losing a parent is one of life's most profound transitions. I navigate a complex tapestry of emotions — sadness, gratitude, and growth."},
        ], clue:"Authentic grief is specific. It lives in small, embarrassing, particular moments.",
        liar:"Post B", explanation:"Post B uses generic, elevated language. Post A has the painfully specific detail of reaching the 'M' in contacts. That's human." },
      { type:"CONSPIRACY_OR_FACT", title:"Strange but True?",
        setup:"One claim is a documented historical fact. The other is fabricated. Which is REAL?",
        statements:[
          {name:"Claim A",text:"The CIA ran MKUltra — testing LSD and mind-control on unwitting US citizens — for over a decade."},
          {name:"Claim B",text:"The US government seeded clouds over the Pacific Northwest in the 1970s to suppress liberal voter turnout."},
        ], clue:"Real conspiracies leave paper trails someone eventually finds.",
        liar:"Claim B", explanation:"MKUltra is documented in declassified CIA files from 1977. The cloud-seeding voter story has no evidence trail — it's fabricated." },
      { type:"WHO_IS_LYING", title:"The Broken Vase",
        setup:"A family heirloom vase is shattered. Three kids were home alone.",
        statements:[
          {name:"Emma",text:"I was upstairs doing homework. I heard the crash and ran down."},
          {name:"Jake",text:"I was in the kitchen the whole time making a sandwich. Didn't hear anything until Emma screamed."},
          {name:"Lily",text:"I was outside in the backyard. Came in after it already happened."},
        ], clue:"The kitchen is right next to where the vase stood. A loud crash there would be impossible to miss.",
        liar:"Jake", explanation:"Jake said he was in the kitchen — right beside the vase — yet claims he heard nothing until Emma screamed. That's not believable. He broke it." },
      { type:"BODY_LANGUAGE", title:"The Apology",
        setup:"A friend apologizes for missing your birthday. Read the cues — are they being sincere?",
        statements:[
          {name:"Observation 1",text:"They made full eye contact and their shoulders dropped as they spoke."},
          {name:"Observation 2",text:"They named the specific thing they missed and didn't make excuses."},
          {name:"Observation 3",text:"Their facial expression matched their words — genuine regret, sustained."},
        ], clue:"Sincere apologies show congruence: the words, face, and body all say the same thing.",
        liar:"They are sincere", explanation:"All three signals align — relaxed posture, specificity, sustained matching expression. This is what genuine remorse looks like. Trust it." },
      { type:"AI_OR_HUMAN", title:"The Restaurant Review",
        setup:"One review was written by a real diner, one by an AI. Spot the fake.",
        statements:[
          {name:"Review A",text:"Best meal of my life. The ambiance was perfect and the staff provided exceptional service throughout our delightful dining experience."},
          {name:"Review B",text:"Waited 40 min for a table but the carbonara was worth it. Our waiter Danny kept checking if we needed more bread. We did. We always do."},
        ], clue:"Real reviews have friction — small complaints, names, oddly specific details.",
        liar:"Review A", explanation:"Review A is frictionless marketing language. Review B has a wait time, a named waiter, and a self-deprecating bread joke. Real people remember the bread." },
      { type:"CONSPIRACY_OR_FACT", title:"Animal Facts",
        setup:"One of these animal claims is true. The other is made up. Which is REAL?",
        statements:[
          {name:"Claim A",text:"Octopuses have three hearts and blue blood."},
          {name:"Claim B",text:"Giraffes cannot make any vocal sounds and are completely mute their entire lives."},
        ], clue:"Nature is stranger than fiction — but absolute claims ('completely,' 'never') are often where myths hide.",
        liar:"Claim B", explanation:"Octopuses really do have three hearts and copper-based blue blood. Giraffes can hum, snort, and grunt — they're not mute. The absolute claim was the fake." },
      { type:"WHO_IS_LYING", title:"The Late Project",
        setup:"A group project is late. Each member explains their part.",
        statements:[
          {name:"Tom",text:"I finished my section Tuesday and emailed it to everyone that night."},
          {name:"Priya",text:"I never got Tom's email. I waited all week for his part before I could start mine."},
          {name:"Alex",text:"I got Tom's email Tuesday and built my section on top of it Wednesday."},
        ], clue:"If Tom emailed everyone, and Alex received it, then one person's story doesn't fit.",
        liar:"Priya", explanation:"Tom emailed everyone; Alex confirms receiving it Tuesday. If the email went out, Priya got it too. Her 'never received it' excuse doesn't hold." },
      { type:"BODY_LANGUAGE", title:"The Salesperson",
        setup:"A car salesperson swears this is the best deal available. Are they hiding something?",
        statements:[
          {name:"Observation 1",text:"They glanced at the door twice while quoting the 'final' price."},
          {name:"Observation 2",text:"Their speech sped up noticeably when you asked about the warranty."},
          {name:"Observation 3",text:"They covered their mouth briefly right after saying 'this is our lowest offer.'"},
        ], clue:"Covering the mouth after a statement is a classic unconscious signal of withholding.",
        liar:"They are hiding something", explanation:"Glancing at exits, accelerated speech under questioning, and mouth-covering after a key claim — three stress signals clustered around the price. There's more room to negotiate." },
      { type:"AI_OR_HUMAN", title:"The Text Breakup",
        setup:"One breakup text is real, one was AI-generated. Which is the human?",
        statements:[
          {name:"Text A",text:"I've been doing a lot of reflecting and I think we want different things. I'll always cherish what we had. I wish you nothing but happiness."},
          {name:"Text B",text:"i can't keep doing the thing where you say you'll call and don't. i waited up again last night. i'm done waiting. i'm sorry."},
        ], clue:"Real pain is messy and specific. Closure-speak is suspiciously tidy.",
        liar:"Text A", explanation:"Text A is a greeting-card template — 'cherish what we had,' 'nothing but happiness.' Text B has a specific grievance, lowercase exhaustion, and real hurt. That's human." },
    ]
  },
  {
    id: 2,
    name: "The Investigator",
    tagline: "The lies get more convincing",
    difficulty: "Easy-Medium",
    color: "#E8A030",
    scenarios: [
      { type:"WHO_IS_LYING", title:"The Last Text",
        setup:"A woman says she never received a threatening text. Records show it was opened. Three people had access to a spoofed number.",
        statements:[
          {name:"Ryan",text:"I was traveling that weekend. I have boarding passes and hotel receipts."},
          {name:"Claire",text:"We hadn't spoken in weeks. I have no reason to threaten her."},
          {name:"James",text:"I was angry that week, I'll admit. But I didn't send anything. I know how this looks."},
        ], clue:"'I know how this looks' is preemptive defense — it assumes guilt before being accused.",
        liar:"James", explanation:"Ryan has alibi evidence. Claire denies motive directly. James volunteers that he looks guilty — innocent people rarely frame their own guilt unprompted." },
      { type:"BODY_LANGUAGE", title:"The Interview",
        setup:"A job candidate is asked why she left her last role. Is she hiding something?",
        statements:[
          {name:"Observation 1",text:"She smiled before answering — but the smile faded before she finished her first sentence."},
          {name:"Observation 2",text:"She leaned forward describing her new goals, but leaned back when referencing her former manager."},
          {name:"Observation 3",text:"She said 'time for a new challenge' while touching her collarbone and breaking eye contact for one second."},
        ], clue:"The body leaks truth in clusters, not isolated signals.",
        liar:"She is hiding something", explanation:"A vanishing smile, postural retreat at the mention of her manager, and self-soothing touch with gaze aversion — three signals cluster around that manager. Something happened there." },
      { type:"AI_OR_HUMAN", title:"The Poem",
        setup:"One of these short poems was written by a person, one by an AI. Which is human?",
        statements:[
          {name:"Poem A",text:"The moonlight dances on the silver sea / A timeless beauty for all eyes to see / Nature's embrace, eternal and divine / In this sacred moment, peace is mine."},
          {name:"Poem B",text:"my grandmother's hands / smelled like onions and Jergens / I'd know them in the dark / I look for them in mine now"},
        ], clue:"AI poetry reaches for 'timeless' and 'divine.' Human poetry reaches for onions and Jergens.",
        liar:"Poem A", explanation:"Poem A is a stack of poetic clichés — moonlight, silver sea, divine, sacred. Poem B has a specific scent memory and grief hiding in the last line. That specificity is human." },
      { type:"CONSPIRACY_OR_FACT", title:"Historical Oddities",
        setup:"One of these historical claims is documented fact. Which is REAL?",
        statements:[
          {name:"Claim A",text:"In 1962, a contagious laughter epidemic in Tanganyika forced schools to close for months."},
          {name:"Claim B",text:"In 1955, the city of Boston banned the color red from all public buildings to reduce citizen aggression."},
        ], clue:"Truth is often weirder than the plausible-sounding fake.",
        liar:"Claim B", explanation:"The Tanganyika laughter epidemic of 1962 is real and well-documented — a mass psychogenic illness. The Boston red-ban story is invented; it sounds plausible but never happened." },
      { type:"WHO_IS_LYING", title:"The Missing Funds",
        setup:"$500 is missing from a shared house fund. Three roommates had the key.",
        statements:[
          {name:"Nina",text:"I haven't touched the box since I put rent in last month. I keep my key on my work lanyard."},
          {name:"Carlos",text:"I opened it Saturday to add my share. The cash was all there when I closed it."},
          {name:"Beth",text:"I never even knew where we kept the spare key, honestly."},
        ], clue:"Beth has lived in the house for two years and contributed to the fund every month.",
        liar:"Beth", explanation:"Beth claims she never knew where the key was — but she's contributed to the fund monthly for two years, which requires accessing the box. The feigned ignorance gives her away." },
      { type:"AI_OR_HUMAN", title:"The Customer Complaint",
        setup:"One complaint email is from a real frustrated customer, one is AI. Which is human?",
        statements:[
          {name:"Email A",text:"I am writing to express my profound disappointment with your service. This experience has been most unsatisfactory and I expect a prompt resolution."},
          {name:"Email B",text:"This is the THIRD time I've called. Your guy Steve promised a callback Monday. It's Thursday. I'm not mad, I'm just tired. Please. Just fix the router."},
        ], clue:"Real anger has a history, a timeline, and a Steve.",
        liar:"Email A", explanation:"Email A is formal and hollow — 'profound disappointment,' 'most unsatisfactory.' Email B has a call count, a named rep, a day-of-week, and that exhausted 'Please.' Real frustration." },
      { type:"BODY_LANGUAGE", title:"The Witness",
        setup:"A witness describes a suspect to police. Are they confident or fabricating?",
        statements:[
          {name:"Observation 1",text:"When asked the suspect's height, they paused, looked up-left, then answered slowly."},
          {name:"Observation 2",text:"They described the jacket color instantly and without hesitation."},
          {name:"Observation 3",text:"When pressed on the face, they said 'I think' twice and shifted in their seat."},
        ], clue:"Genuine memory is uneven — vivid in some details, hazy in others. Fabrication tends to be uniformly smooth or uniformly vague.",
        liar:"They genuinely saw the jacket", explanation:"The instant, hesitation-free jacket recall is real memory. The hedging on height and face ('I think,' seat-shifting) shows where memory fades — which is normal for a true account." },
      { type:"WHO_IS_LYING", title:"The Group Trip",
        setup:"Someone canceled the group's hotel booking. Three friends had the login.",
        statements:[
          {name:"Maya",text:"I never log into that account from my phone. Only my laptop, and it's been in the shop all week."},
          {name:"Jordan",text:"I logged in Monday to check the dates but I swear I didn't cancel anything."},
          {name:"Sam",text:"I don't even remember the password. Jordan always handles the bookings."},
        ], clue:"The cancellation came from a mobile device on Tuesday.",
        liar:"Maya", explanation:"The cancellation came from a phone on Tuesday. Maya insists she only uses her laptop — which was in the shop — making her the one who'd most want to rule out mobile access. The overly specific alibi points to her." },
      { type:"CONSPIRACY_OR_FACT", title:"Space Claims",
        setup:"One of these space facts is true. Which is REAL?",
        statements:[
          {name:"Claim A",text:"There is a planet where it rains molten glass sideways at 5,400 mph winds."},
          {name:"Claim B",text:"Astronauts on the ISS can see individual car headlights on Earth at night with the naked eye."},
        ], clue:"One of these violates the basic physics of human vision from orbit.",
        liar:"Claim B", explanation:"Planet HD 189733b really does rain molten glass sideways in brutal winds. But individual car headlights are far too small to resolve from the ISS — that claim is false." },
      { type:"AI_OR_HUMAN", title:"The Dating Profile",
        setup:"One dating bio was written by a person, one by AI. Which is human?",
        statements:[
          {name:"Bio A",text:"Adventurous soul who loves travel, good food, and meaningful connections. Looking for someone genuine to share life's beautiful moments with."},
          {name:"Bio B",text:"I will judge you (lovingly) for putting ketchup on eggs. I cry at dog commercials. Ask me about the time I got banned from a Chuck E Cheese."},
        ], clue:"AI writes the bio everyone writes. Humans bring the Chuck E Cheese ban.",
        liar:"Bio A", explanation:"Bio A is the universal template — 'adventurous,' 'meaningful connections,' 'beautiful moments.' Bio B has a specific opinion, a confessed weakness, and a story hook. Memorably human." },
      { type:"WHO_IS_LYING", title:"The Spilled Secret",
        setup:"A private secret got out. Three people were told in confidence.",
        statements:[
          {name:"Dana",text:"I never repeat things. I didn't even tell my husband, and I tell him everything."},
          {name:"Raj",text:"I forgot you even told me that, honestly. It wasn't important enough for me to remember."},
          {name:"Kim",text:"I told one person, but they're not connected to your circle at all, so it couldn't be them."},
        ], clue:"Kim openly admits she retold it — but assumes her listener couldn't be the link.",
        liar:"Kim", explanation:"Kim admits passing it on while assuming her one listener was 'safe.' Secrets travel through unexpected connections. Her confident assumption that the leak 'couldn't be them' is exactly how secrets escape." },
      { type:"BODY_LANGUAGE", title:"The Compliment",
        setup:"A coworker compliments your presentation. Genuine, or covering envy?",
        statements:[
          {name:"Observation 1",text:"Their smile only moved their mouth — the eyes stayed flat and still."},
          {name:"Observation 2",text:"They complimented you, then immediately mentioned their own upcoming project twice."},
          {name:"Observation 3",text:"Their tone dropped slightly on the word 'great,' almost swallowing it."},
        ], clue:"A real smile crinkles the eyes. A social smile stops at the mouth.",
        liar:"The compliment is not genuine", explanation:"The mouth-only smile, the swallowed 'great,' and the immediate pivot to their own project — all signs the praise masks competitiveness. The eyes never joined the smile." },
    ]
  },
  {
    id: 3,
    name: "The Detective",
    tagline: "Trust nothing. Verify everything.",
    difficulty: "Medium",
    color: "#7C3AED",
    scenarios: [
      { type:"WHO_IS_LYING", title:"The Insurance Claim",
        setup:"A man claims his laptop was stolen from his car. The insurer interviews three people who were nearby.",
        statements:[
          {name:"Claimant",text:"I parked, went into the gym for an hour, came back and the window was smashed. Laptop gone."},
          {name:"Gym Clerk",text:"He checked in at 6 but I saw him leave again after just ten minutes. Came back near closing."},
          {name:"Witness",text:"I parked next to a car with a smashed window around 6:30. Didn't see anyone near it."},
        ], clue:"The claimant's timeline and the gym clerk's account don't match on one crucial point.",
        liar:"Claimant", explanation:"The claimant says he was in the gym the whole hour, but the clerk saw him leave after ten minutes. That unaccounted gap — and the mismatched timeline — suggests the claim is staged." },
      { type:"AI_OR_HUMAN", title:"The Apology Letter",
        setup:"A public figure issues an apology. One version is human-written, one AI. Which is human?",
        statements:[
          {name:"Version A",text:"I deeply regret any harm my words may have caused. I am committed to learning and growing from this experience and to being better moving forward."},
          {name:"Version B",text:"I said something cruel about Marcus at the meeting and he wasn't even in the room to defend himself. That was cowardly. I already called him. I owe you all the same honesty."},
        ], clue:"Real accountability names the specific wrong. PR apologies stay abstract.",
        liar:"Version A", explanation:"Version A is the non-apology template — 'any harm,' 'may have caused,' passive and vague. Version B names the person, the act, calls it cowardly, and reports concrete action. Genuine accountability." },
      { type:"BODY_LANGUAGE", title:"The Poker Game",
        setup:"A player makes a huge bet. Read the tells — strong hand or bluff?",
        statements:[
          {name:"Observation 1",text:"After betting, they went completely still — no fidgeting, barely breathing."},
          {name:"Observation 2",text:"They placed their chips down gently and deliberately, not with force."},
          {name:"Observation 3",text:"They stared a beat too long at you after the bet, then looked away first."},
        ], clue:"In poker, sudden stillness after aggression often means weakness — strength tends to relax, not freeze.",
        liar:"They are bluffing", explanation:"Freezing after a big bet is the classic bluff tell — the bluffer suppresses all movement to avoid 'giving away' anything. Genuine strength is usually looser. The held breath and forced stare confirm it." },
      { type:"CONSPIRACY_OR_FACT", title:"Medical History",
        setup:"One of these medical history claims is real. Which is REAL?",
        statements:[
          {name:"Claim A",text:"Doctors once widely prescribed cigarettes to patients to help with stress and even throat irritation."},
          {name:"Claim B",text:"In the 1940s, radioactive water was sold in pharmacies as a cure for baldness with a money-back guarantee."},
        ], clue:"Both sound absurd by modern standards — but only one happened.",
        liar:"Claim B", explanation:"Cigarettes were genuinely marketed and even doctor-recommended for decades. Radioactive water tonics existed (like Radithor), but they were sold as energy cures, not baldness treatments with guarantees — that detail is fabricated." },
      { type:"WHO_IS_LYING", title:"The Forged Signature",
        setup:"A contract has a forged signature. Three people had access to the document.",
        statements:[
          {name:"Helen",text:"I was on vacation in another country the entire week the contract was signed. I have stamps in my passport."},
          {name:"Victor",text:"I notarized dozens of documents that day. I genuinely can't recall this specific one, but I follow protocol every time."},
          {name:"Grace",text:"I would never forge anything. I didn't even handle that contract — it went straight from Victor to the client."},
        ], clue:"Grace claims the contract went 'straight from Victor to the client' — but how would she know its exact path if she never handled it?",
        liar:"Grace", explanation:"Grace says she never handled the contract — yet describes its exact route in detail. You can't have intimate knowledge of a document's path you supposedly never touched. The contradiction exposes her." },
      { type:"AI_OR_HUMAN", title:"The Childhood Memory",
        setup:"One person is recounting a real childhood memory, one is AI-generated. Which is human?",
        statements:[
          {name:"Account A",text:"Summers at my grandparents' were magical. We'd play outside until dusk, catch fireflies, and make cherished memories that I'll treasure forever."},
          {name:"Account B",text:"My grandpa had this gross peppermint he kept in his shirt pocket. Lint and all. He'd offer me one like it was treasure. I always took it. I'd give anything for one now."},
        ], clue:"Nostalgia in the abstract is AI. The lint on the peppermint is human.",
        liar:"Account A", explanation:"Account A is greeting-card nostalgia — 'magical,' 'cherished memories,' 'treasure forever.' Account B has a lint-covered peppermint and grief in the final line. Real memory keeps the gross, specific details." },
      { type:"BODY_LANGUAGE", title:"The Reunion",
        setup:"An old friend says they're thrilled to see you after years. Genuine warmth or social performance?",
        statements:[
          {name:"Observation 1",text:"Their eyebrows flashed up briefly the instant they saw you, before they even spoke."},
          {name:"Observation 2",text:"They reached for a hug and their feet pointed fully toward you the whole conversation."},
          {name:"Observation 3",text:"Their first words came a half-second after a genuine, eye-crinkling smile."},
        ], clue:"The unconscious 'eyebrow flash' of recognition is nearly impossible to fake and happens before conscious thought.",
        liar:"They are genuinely happy", explanation:"The involuntary eyebrow flash, feet pointed toward you (a true engagement signal), and the eye-crinkling smile that preceded speech — all authentic. This is real delight, not performance." },
      { type:"WHO_IS_LYING", title:"The Plagiarism",
        setup:"Two students submit nearly identical essays. Both claim originality. A third saw what happened.",
        statements:[
          {name:"Student A",text:"I wrote mine three weeks ago. I can show you the document history with timestamps."},
          {name:"Student B",text:"I wrote mine the night before it was due. Pure inspiration. I don't know how it's similar."},
          {name:"Witness",text:"I saw Student B in the library with a printout, typing fast and glancing at it the whole time."},
        ], clue:"Student A offers verifiable evidence. Student B offers 'inspiration' and the witness saw them copying from a printout.",
        liar:"Student B", explanation:"Student A can prove a three-week timeline with document history. Student B claims last-minute 'inspiration' produced an identical essay — and the witness saw them copying from a printout. Student B plagiarized." },
      { type:"CONSPIRACY_OR_FACT", title:"Technology Origins",
        setup:"One of these tech-history claims is true. Which is REAL?",
        statements:[
          {name:"Claim A",text:"The first computer programmer in history was a woman, Ada Lovelace, in the 1840s — before computers physically existed."},
          {name:"Claim B",text:"The '@' symbol in email was chosen by a NASA committee after a two-year study of 300 candidate symbols."},
        ], clue:"One of these has a single, well-documented inventor making a quick practical choice.",
        liar:"Claim B", explanation:"Ada Lovelace really did write the first algorithm for Babbage's theoretical engine in the 1840s. The '@' in email was picked by Ray Tomlinson in 1971 because it was already on the keyboard and unused in names — no NASA committee." },
      { type:"AI_OR_HUMAN", title:"The Recipe Intro",
        setup:"One recipe introduction was written by a home cook, one by AI. Which is human?",
        statements:[
          {name:"Intro A",text:"This delightful dish brings together fresh, wholesome ingredients for a meal the whole family will love. Perfect for any occasion!"},
          {name:"Intro B",text:"My mom made this every time someone got dumped. It's basically just cheese and carbs but I've never once felt sad while eating it. Burns easily, watch the heat."},
        ], clue:"AI recipe intros sell. Human ones come with a story and a warning.",
        liar:"Intro A", explanation:"Intro A is recipe-blog filler — 'delightful,' 'wholesome,' 'the whole family will love.' Intro B has an emotional origin, honest self-awareness about the ingredients, and a practical warning. Human." },
      { type:"BODY_LANGUAGE", title:"The Negotiation",
        setup:"During a salary negotiation, your manager says the budget is 'completely maxed out.' True, or a tactic?",
        statements:[
          {name:"Observation 1",text:"They broke eye contact and looked at their notes when saying 'completely maxed out.'"},
          {name:"Observation 2",text:"Their hand briefly touched the back of their neck as they delivered the figure."},
          {name:"Observation 3",text:"They answered your counter-question a beat faster than felt natural, almost rehearsed."},
        ], clue:"Neck-touching is a pacifying gesture — the body self-soothing during a stressful or untrue statement.",
        liar:"There is more budget", explanation:"Broken eye contact on the key claim, a neck-touch pacifier, and a suspiciously rehearsed rebuttal — the cluster suggests 'maxed out' isn't the full truth. There's likely more room." },
      { type:"WHO_IS_LYING", title:"The Double Booking",
        setup:"A venue was double-booked for the same evening. Three staff handled reservations.",
        statements:[
          {name:"Owen",text:"I booked the Patel wedding in the morning and marked the calendar immediately, like always."},
          {name:"Tara",text:"I took the corporate event call in the afternoon. The calendar showed the date as open when I checked."},
          {name:"Wes",text:"I haven't touched the booking calendar in weeks. I only work the kitchen now."},
        ], clue:"If Owen marked the calendar in the morning, it could not have shown 'open' to Tara in the afternoon — unless someone changed it.",
        liar:"Owen", explanation:"Owen claims he marked the calendar immediately in the morning. But Tara saw it open in the afternoon. Either Owen never actually logged it, or he's lying about doing so 'like always.' His story breaks the timeline." },
    ]
  },
  {
    id: 4,
    name: "The Profiler",
    tagline: "They've studied how to lie to you",
    difficulty: "Medium-Hard",
    color: "#E8A030",
    scenarios: [
      { type:"WHO_IS_LYING", title:"The DARVO Defense",
        setup:"After being confronted about a hurtful comment, someone responds. One of three statements uses DARVO (Deny, Attack, Reverse Victim & Offender).",
        statements:[
          {name:"Response A",text:"You're right, I did say that, and it was unfair of me. I'm sorry. Can we talk about why?"},
          {name:"Response B",text:"I never said that. And honestly, I'm hurt you'd even accuse me. After everything I do for you, this is how you treat me?"},
          {name:"Response C",text:"I don't remember saying it exactly that way, but if it landed badly, I want to understand. Tell me what you heard."},
        ], clue:"DARVO flips the script: deny it happened, attack the accuser, then claim to be the real victim.",
        liar:"Response B", explanation:"Response B is textbook DARVO: Denies ('I never said that'), Attacks ('I'm hurt you'd accuse me'), and Reverses victim/offender ('after everything I do, THIS is how you treat ME'). A manipulation tactic, not a defense." },
      { type:"BODY_LANGUAGE", title:"The Charmer",
        setup:"Someone is laying on intense charm and flattery very early. Genuine connection or love-bombing?",
        statements:[
          {name:"Observation 1",text:"Within an hour they called you their 'soulmate' and said they'd never felt this way before."},
          {name:"Observation 2",text:"Their compliments escalated fast and grew uncomfortable when you didn't reciprocate equally."},
          {name:"Observation 3",text:"They mirrored your every gesture and opinion almost instantly, agreeing with everything."},
        ], clue:"Love-bombing moves faster than real intimacy can. Genuine connection doesn't demand reciprocation on a timeline.",
        liar:"This is love-bombing", explanation:"'Soulmate' within an hour, escalating flattery that turns uncomfortable when not matched, and instant total mirroring — these are love-bombing signals. Real intimacy builds slowly and tolerates difference." },
      { type:"AI_OR_HUMAN", title:"The Wikipedia Edit",
        setup:"One paragraph is from a real Wikipedia article, one was AI-generated to mimic the style. Which is the genuine human-edited entry?",
        statements:[
          {name:"Entry A",text:"The bridge, completed in 1932, remains a vital transit link. It is widely regarded as an architectural marvel and continues to inspire admiration from visitors worldwide."},
          {name:"Entry B",text:"The bridge opened in 1932, three years behind schedule. A 1987 inspection found significant corrosion in the eastern truss, prompting a contentious two-year closure. Locals nicknamed it 'the Rust Belt.'[14]"},
        ], clue:"Real encyclopedia entries have dates, controversies, citations, and unflattering details. AI mimics tone but smooths over the messy specifics.",
        liar:"Entry A", explanation:"Entry A is vague praise — 'marvel,' 'admiration worldwide' — with no facts. Entry B has a delay, a dated inspection, a controversy, a nickname, and a citation marker. That specificity and neutrality is genuine encyclopedia writing." },
      { type:"WHO_IS_LYING", title:"The Embezzlement",
        setup:"Funds were skimmed over months. Three executives are interviewed by an auditor.",
        statements:[
          {name:"CFO",text:"I flagged the irregularities myself the moment I noticed them. Why would I report a crime I was committing?"},
          {name:"Controller",text:"I reconcile accounts monthly. The discrepancies were small enough individually to slip past a standard review."},
          {name:"VP Finance",text:"I trust my team completely. I sign off on what they bring me. I don't audit every line — that's not my job."},
        ], clue:"The skimming was done in amounts small enough to evade exactly the kind of 'standard monthly review' one person described in oddly precise detail.",
        liar:"Controller", explanation:"The Controller knows the exact threshold that evades a standard review — and describes the skimming method precisely. Only someone designing the scheme to slip past monthly reconciliation would frame it that way. The expertise betrays them." },
      { type:"BODY_LANGUAGE", title:"The Fake Confidence",
        setup:"A speaker claims total confidence in their failing product. Real conviction or mask?",
        statements:[
          {name:"Observation 1",text:"Their words were bold but their voice rose in pitch on every key claim."},
          {name:"Observation 2",text:"They gripped the podium edge so hard their knuckles paled, while smiling broadly."},
          {name:"Observation 3",text:"They over-laughed at a tough question, a beat too loud, before answering vaguely."},
        ], clue:"Vocal pitch tends to rise under stress, regardless of the confident words being spoken. The body contradicts the script.",
        liar:"They are masking doubt", explanation:"Rising pitch on every claim, a white-knuckle grip beneath the smile, and over-loud laughter deflecting hard questions — the body is flooded with stress the words deny. The confidence is a mask." },
      { type:"CONSPIRACY_OR_FACT", title:"Government Programs",
        setup:"One of these declassified government programs is real. Which is REAL?",
        statements:[
          {name:"Claim A",text:"The US Army once seriously researched a 'gay bomb' — a chemical weapon to make enemy soldiers irresistibly attracted to each other."},
          {name:"Claim B",text:"The UK government secretly trained pigeons to carry tiny cameras and photograph Soviet installations during the Cold War, deploying over 2,000 birds."},
        ], clue:"Both sound like satire — but one appears in actual declassified documents.",
        liar:"Claim B", explanation:"The 'gay bomb' was a real proposed concept in a 1994 US Air Force document — bizarre but documented. The mass pigeon-camera spy program with 2,000 deployed birds is fabricated; pigeon photography existed in WWI era but not this Cold War operation." },
      { type:"WHO_IS_LYING", title:"The Strategic Truth",
        setup:"A suspect in a theft tells mostly the truth to hide one lie. Three statements — one contains the buried deception.",
        statements:[
          {name:"Statement A",text:"Yes, I was in the building that night. I badged in at 7, everyone saw me, I'm not going to pretend otherwise."},
          {name:"Statement B",text:"I went to the third floor to grab my charger, then straight back down. Two minutes, tops."},
          {name:"Statement C",text:"I'll be completely honest — I've had money problems lately. I'm not hiding that. But I didn't take anything."},
        ], clue:"Skilled liars volunteer uncomfortable truths to build credibility, then bury the lie in a verifiable-sounding specific.",
        liar:"Statement B", explanation:"Statements A and C volunteer damaging truths (presence, motive) to seem honest. Statement B is the buried lie — the oddly precise 'two minutes, tops' to the floor where the theft occurred. The specificity is doing the deceiving." },
      { type:"AI_OR_HUMAN", title:"The Eulogy",
        setup:"One eulogy excerpt was written by a grieving family member, one by AI. Which is human?",
        statements:[
          {name:"Excerpt A",text:"He was a beloved father, a devoted husband, and a pillar of his community. His warmth touched all who knew him, and his legacy will live on in our hearts forever."},
          {name:"Excerpt B",text:"Dad couldn't sing but he sang anyway, loudly, in the car, getting the words wrong on purpose to make us groan. I'd give anything to be annoyed by him one more time."},
        ], clue:"Funeral-template language describes a person. Real grief remembers one specific, imperfect, annoying thing.",
        liar:"Excerpt A", explanation:"Excerpt A is the universal eulogy — 'beloved,' 'pillar,' 'legacy,' 'forever.' Excerpt B has a specific, imperfect habit (bad singing on purpose) and grief that wishes for the annoyance back. That's a real person being mourned." },
      { type:"BODY_LANGUAGE", title:"The Guilty Helper",
        setup:"After a break-in, a neighbor is very eager to help with the investigation. Genuine concern or guilty over-involvement?",
        statements:[
          {name:"Observation 1",text:"They volunteered theories before being asked any questions, very quickly."},
          {name:"Observation 2",text:"They mentioned three times, unprompted, that they 'weren't even home' that night."},
          {name:"Observation 3",text:"When the officer changed subjects, they steered it back to their own alibi twice."},
        ], clue:"Unprompted, repeated alibi assertions — when no one has accused you — often signal guilt, not innocence.",
        liar:"They are over-asserting innocence", explanation:"Volunteering theories before being asked, repeating 'I wasn't home' three times unprompted, and steering back to their own alibi — these are signs of guilty over-involvement. The innocent don't usually defend an accusation no one made." },
      { type:"WHO_IS_LYING", title:"The Inheritance",
        setup:"A will was altered shortly before death. Three relatives had access during the final week.",
        statements:[
          {name:"Daughter",text:"I was at the hospital every single day. The nurses can confirm I never left her side."},
          {name:"Nephew",text:"I visited once, on Tuesday. I barely knew where she kept her papers, let alone the will."},
          {name:"Caretaker",text:"I handled her correspondence daily, but I'd never touch legal documents. That's not my place, and I respected her completely."},
        ], clue:"The caretaker handled correspondence daily and had the most consistent, unsupervised access to her papers — yet emphasizes 'respect' over opportunity.",
        liar:"Caretaker", explanation:"The caretaker had daily, unsupervised access to her papers — the most opportunity by far — yet deflects with emotional language about 'respect' and 'place' rather than addressing access. The appeal to character over opportunity is the tell." },
      { type:"AI_OR_HUMAN", title:"The Product Review",
        setup:"One detailed product review is genuine, one is an AI-written fake designed to look credible. Which is human?",
        statements:[
          {name:"Review A",text:"After extensive testing, I can confidently say this product exceeds expectations in every category. The build quality is superb and performance is flawless. Highly recommend to anyone!"},
          {name:"Review B",text:"Works great EXCEPT the app disconnects if your wifi blips. Took me a week to figure out that was the issue and not the device. Four stars. Would be five if the app wasn't held together with tape."},
        ], clue:"AI fakes credibility with 'extensive testing' and 'every category.' Real reviews have one specific, hard-won frustration.",
        liar:"Review A", explanation:"Review A performs credibility — 'extensive testing,' 'flawless,' 'every category' — without a single specific. Review B has a precise bug, the time it took to diagnose, a docked star, and a memorable metaphor. Genuine experience." },
      { type:"BODY_LANGUAGE", title:"The Rehearsed Story",
        setup:"Someone recounts their whereabouts during an incident. Is the account lived or rehearsed?",
        statements:[
          {name:"Observation 1",text:"They told the story in perfect chronological order with no backtracking or self-correction."},
          {name:"Observation 2",text:"When asked to tell it backwards, from end to start, they froze and stumbled badly."},
          {name:"Observation 3",text:"The emotional beats felt placed rather than felt — a smile arriving slightly after the funny part."},
        ], clue:"Real memories can be recalled out of order. Rehearsed scripts fall apart when you ask for them in reverse.",
        liar:"The story is rehearsed", explanation:"Genuine memory is messy and can be accessed non-linearly; a rehearsed script is memorized forward only. The reverse-order collapse, the too-perfect sequence, and the mistimed emotions all point to fabrication." },
    ]
  },
  {
    id: 5,
    name: "The Interrogator",
    tagline: "The masters. No tells. No mercy.",
    difficulty: "Hard",
    color: "#E83050",
    scenarios: [
      { type:"WHO_IS_LYING", title:"The Perfect Alibi",
        setup:"A high-stakes theft. Three suspects, each with a seemingly airtight alibi. One alibi is too perfect.",
        statements:[
          {name:"Suspect A",text:"I was at dinner with friends. Here's the receipt, timestamped 8:42, and four people who'll vouch for me."},
          {name:"Suspect B",text:"I honestly can't account for every minute. I was home, alone, probably watching TV. I know that sounds weak."},
          {name:"Suspect C",text:"I was at the gym from 7 to 9. Front desk log, my locker entry, two gym buddies, and the parking camera all confirm it. Every minute is covered."},
        ], clue:"An alibi where 'every single minute is covered' by multiple independent sources can indicate deliberate construction. Truthful people usually have gaps.",
        liar:"Suspect C", explanation:"Suspect B's honest, unflattering 'I can't account for everything' rings true — real life has gaps. Suspect C's alibi is suspiciously airtight, with redundant independent proof for every minute. Over-construction suggests it was built in advance." },
      { type:"BODY_LANGUAGE", title:"The Trained Liar",
        setup:"A practiced manipulator is being questioned. They've eliminated the obvious tells. What gives them away?",
        statements:[
          {name:"Observation 1",text:"They maintained deliberate, unbroken eye contact — more than feels natural in normal conversation."},
          {name:"Observation 2",text:"Their gestures came a fraction of a second AFTER their words, instead of with them."},
          {name:"Observation 3",text:"They showed zero of the normal small self-corrections and hesitations of honest recall."},
        ], clue:"Trained liars over-correct. They suppress natural tells so thoroughly that the absence of normal imperfection becomes the tell.",
        liar:"They are lying", explanation:"This person has scrubbed the obvious tells — but over-corrected. Forced, excessive eye contact, gestures lagging behind speech (a sign of fabrication, not feeling), and an unnatural absence of honest hesitation. The too-smooth performance is itself the tell." },
      { type:"AI_OR_HUMAN", title:"The Indistinguishable",
        setup:"Both passages were crafted to be nearly indistinguishable. One is human, one is a top-tier AI. Find the human.",
        statements:[
          {name:"Passage A",text:"The thing nobody tells you about caregiving is the boredom. Everyone warns you about grief. No one mentions the Tuesday afternoons that last a thousand years, the way you start to resent the silence and then hate yourself for it."},
          {name:"Passage B",text:"Caregiving teaches you about the quiet moments. The unglamorous in-between hours reveal a profound truth: love is not always grand gestures, but presence — sitting in the silence, holding space for another soul."},
        ], clue:"AI resolves discomfort into wisdom ('a profound truth'). Humans sit in the ugly, unresolved feeling and admit the shameful part.",
        liar:"Passage B", explanation:"Passage B turns difficulty into tidy inspiration — 'profound truth,' 'holding space for another soul.' Passage A admits something shameful and unresolved: resentment, self-hatred, boredom that doesn't get redeemed. AI seeks the lesson; humans confess the mess." },
      { type:"WHO_IS_LYING", title:"The Insider",
        setup:"Confidential information leaked to a competitor. Three people had access. Each gives a sophisticated denial.",
        statements:[
          {name:"Engineer",text:"I had access, yes. But I'd been trying to LEAVE for that competitor for months — leaking would've sabotaged my own job offer. It makes no sense for me."},
          {name:"Manager",text:"I'll be transparent: I was furious about my bonus that quarter. I had motive. But motive isn't action, and I didn't act on it."},
          {name:"Analyst",text:"I barely understood the technical documents. Even if I'd wanted to leak, I wouldn't have known which files mattered or what I was looking at."},
        ], clue:"The analyst claims ignorance of which files mattered — but the leak consisted of precisely the right files, selected with clear understanding.",
        liar:"Analyst", explanation:"The leaked files were precisely the valuable ones, selected with clear understanding. The analyst's defense — 'I wouldn't have known which files mattered' — is contradicted by the surgical precision of the leak. The feigned incompetence is the lie; the others' candid admissions of motive are disarming honesty." },
      { type:"CONSPIRACY_OR_FACT", title:"The Plausible Fake",
        setup:"Both claims are designed to sound equally credible. One is documented history. Which is REAL?",
        statements:[
          {name:"Claim A",text:"During WWII, the Allies built an entire fake army — inflatable tanks, fake radio traffic, recorded sounds of troops — to deceive the Germans about the D-Day location."},
          {name:"Claim B",text:"During the Cold War, the US Mint secretly produced 50,000 counterfeit Soviet rubles to destabilize the USSR's economy, a program called Operation Greenback."},
        ], clue:"One of these is among the most famous military deceptions in history; the other borrows that plausibility to sound real.",
        liar:"Claim B", explanation:"The 'Ghost Army' — inflatable tanks, sound trucks, fake radio traffic — was real and is well-documented (Operation Fortitude / the 23rd HQ Special Troops). 'Operation Greenback' counterfeiting rubles is fabricated, designed to sound like a plausible Cold War op." },
      { type:"WHO_IS_LYING", title:"The Counter-Accusation",
        setup:"Two business partners each accuse the other of stealing from the company. A forensic accountant reviews their statements. One is the actual thief, deflecting.",
        statements:[
          {name:"Partner A",text:"I noticed the discrepancies and hired the accountant myself. I'm the one who brought this to light. Now suddenly I'm the suspect?"},
          {name:"Partner B",text:"The missing amounts match transactions only A could authorize. I can't prove intent, but the access logs speak for themselves. Check them."},
        ], clue:"One partner points to verifiable evidence (access logs). The other relies on the optics of 'I reported it' — a classic preemptive cover.",
        liar:"Partner A", explanation:"Partner B points to objective, checkable evidence: the amounts match transactions only A could authorize. Partner A relies on the optics of having 'reported it first' — a known tactic where the guilty party initiates the investigation to appear innocent. The access logs, not the narrative, hold the truth." },
      { type:"BODY_LANGUAGE", title:"The Micro-Expression",
        setup:"A suspect keeps perfect composure throughout. But one fleeting micro-expression betrays the truth. Which detail matters?",
        statements:[
          {name:"Observation 1",text:"For 1/15th of a second, when shown the victim's photo, one corner of their mouth pulled down and sideways before the calm mask returned."},
          {name:"Observation 2",text:"They maintained a calm, cooperative, pleasant demeanor for the entire two-hour interview."},
          {name:"Observation 3",text:"They answered every question in a measured, even, untroubled tone."},
        ], clue:"Micro-expressions last a fraction of a second and leak the true emotion before the conscious mask reasserts control. They override hours of composure.",
        liar:"Observation 1 reveals the truth", explanation:"The two hours of calm (Obs 2 & 3) are the controlled mask. The 1/15th-second one-sided mouth pull — a micro-expression of contempt or suppressed distress flashing at the victim's photo — is the involuntary leak. A single genuine micro-expression outweighs hours of performance." },
      { type:"AI_OR_HUMAN", title:"The Confession",
        setup:"One of these confessions is from a real person, one is AI imitating raw honesty. The AI has been trained to fake imperfection. Find the human.",
        statements:[
          {name:"Confession A",text:"I lied about it. Not even for a good reason — just because admitting it felt worse in the moment than the lie did. And then it was too late to take back, so I kept going. That's the embarrassing part. There was no master plan. I was just a coward in small increments."},
          {name:"Confession B",text:"I made a mistake, and I own that fully. I wasn't perfect — I stumbled, I hesitated, I even told a small untruth. But I've grown from it, and I'm choosing honesty now, even though it's hard and scary to admit my flaws like this."},
        ], clue:"AI now fakes imperfection — but it still narrates growth and frames flaws as a redemption arc. Real confession often has no arc, just a flat, specific shame.",
        liar:"Confession B", explanation:"Confession B performs vulnerability but can't resist the redemption arc — 'I've grown,' 'choosing honesty now,' flaws as a journey. Confession A has no arc, no growth, just a precise and unflattering mechanism ('a coward in small increments') and flat residual shame. Real confession rarely redeems itself in the telling." },
      { type:"WHO_IS_LYING", title:"The Three Experts",
        setup:"An art forgery passed authentication. Three experts examined it. One knew it was fake and approved it anyway.",
        statements:[
          {name:"Expert A",text:"I focused on the pigment analysis. It was consistent with the period. I had no reason within my specialty to doubt it."},
          {name:"Expert B",text:"The provenance documents were flawless — too flawless, I noted that in my report. But documentation isn't my call to reject; I flagged it and deferred."},
          {name:"Expert C",text:"Everything checked out. The brushwork, the aging, the frame, the canvas, the signature — all completely authentic. I had no hesitation whatsoever signing off."},
        ], clue:"Expert B flagged a concern. Expert A stayed within honest limits. Expert C claims total certainty across every category — including ones outside any single expert's specialty.",
        liar:"Expert C", explanation:"Expert A honestly limits their confidence to their specialty. Expert B even flagged the too-perfect provenance. Expert C claims total certainty across every domain — brushwork, aging, frame, canvas, signature — which no single honest expert would assert. The blanket, hesitation-free approval across all categories reveals someone smoothing it through." },
      { type:"BODY_LANGUAGE", title:"The Calculated Tears",
        setup:"During an emotional plea, someone cries. Genuine grief or strategic performance?",
        statements:[
          {name:"Observation 1",text:"The tears appeared exactly when the audience's attention peaked, then stopped the moment the camera moved away."},
          {name:"Observation 2",text:"Their breathing stayed even and controlled throughout — no genuine catch or hitch in the voice."},
          {name:"Observation 3",text:"They checked the room's reaction between sobs, scanning faces to gauge effect."},
        ], clue:"Genuine crying disrupts breathing and isn't responsive to audience attention. Performed crying is timed and monitored for effect.",
        liar:"The tears are performed", explanation:"Real grief hijacks the breath — there's a catch, a hitch, a loss of control. These tears arrive on cue, stop when unobserved, leave breathing perfectly even, and are punctuated by scanning the room for effect. That's calculated performance, not genuine emotion." },
      { type:"AI_OR_HUMAN", title:"The Final Test",
        setup:"Two reflections on regret. One human, one the most sophisticated AI imitation. Every obvious tell has been removed. Find the human.",
        statements:[
          {name:"Reflection A",text:"I think about the version of me that took the other job sometimes. Not with longing exactly. More like — I want to know if she's happier, and I'm a little afraid the answer is yes, and a little afraid it's no, because I'm not sure which one I could live with better."},
          {name:"Reflection B",text:"Regret, I've come to understand, is not about the past but the present. It's the mind's way of honoring what mattered to us. In learning to sit with regret rather than flee it, I've found an unexpected peace — a deeper acceptance of the beautifully imperfect path I've walked."},
        ], clue:"AI, even at its best, resolves the tension into wisdom and peace. The human leaves it unresolved, holding two contradictory fears at once without solving them.",
        liar:"Reflection B", explanation:"Reflection B arrives at 'unexpected peace' and a 'beautifully imperfect path' — AI's signature move of converting difficulty into serene wisdom. Reflection A never resolves: it holds two contradictory fears simultaneously ('afraid it's yes, afraid it's no') and admits it can't tell which is worse. That unresolved, self-contradicting honesty is unmistakably human." },
    ]
  }
];

if (typeof module !== 'undefined') module.exports = { LEVELS };
